# Server Configuration
server.port=8080

# MongoDB Configuration
# Refers to local mongodb container during compose deployment
spring.data.mongodb.uri=mongodb://mongodb:27017/hospital_agent_db

# Google Gemini API Configuration
# Automatically binds to host GEMINI_API_KEY environment variable
gemini.api.key=${GEMINI_API_KEY:MY_GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
